### ISSUE TITLE
Allowing dependabot access to ldes-client

### ISSUE THREAD

**Issue by WLefever-Cegeka** [Informatievlaanderen/VSDS-LDESClientCli#11]
See

https://docs.github.com/en/organizations/keeping-your-organization-secure/managing-security-settings-for-your-organization/managing-security-and-analysis-settings-for-your-organization#allowing-dependabot-to-access-private-dependencies

**Comment by sverholen** [comment]
Since we're moving to maven central soon, solving this issue is no longer necessary.
