### ISSUE TITLE
Usage instruction in the README

### ISSUE THREAD

**Issue by pietercolpaert** [Informatievlaanderen/VSDS-LDESClientCli#12]
Would love to give this a test spin. Can you add instructions in the README how to run it?

**Comment by WLefever-Cegeka** [comment]
Will update the README.md, but to unblock you right away:
Usage is displayed when running the tool with no parameters or with the explicit "--help":
* docker run ghcr.io/informatievlaanderen/ldes-cli:20220902T0726
* docker run ghcr.io/informatievlaanderen/ldes-cli:20220902T0726 --help

**Comment by MPParsley** [comment]
Also interested in the documentation.

At the moment we're using [@treecg/actor-init-ldes-client](https://github.com/district09/ldes-to-linkedpipes/blob/enhancement/better-ldes/client/package.json#L17).

**Comment by Yalz** [comment]
Hi @pietercolpaert, could you verify the README is up to your standards now?
