### ISSUE TITLE
Wrong Repository for Client SDK Dependency

### ISSUE THREAD

**Issue by Krieke** [Informatievlaanderen/VSDS-LDESClientCli#24]
Shouldn't this project have a dependency on the Client SDK from repository:
* <url>https://maven.pkg.github.com/Informatievlaanderen/VSDS-LDESClient4J</url>

iso 

* <url>https://maven.pkg.github.com/Informatievlaanderen/VSDS-LDESClient-NifiProcessor</url>

**Comment by Yalz** [comment]
This issue has been come obsolete since the dependency is now referring to the client sdk
